# Generated by Django 5.2.17 on 2026-08-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(help_text="13 Character <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>", max_length=13, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
